remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Data challenge global OSE
#logo: figures/dc_2023_ose_global_duacs_sla_map.jpg
description: This repository contains codes and sample notebooks for downloading and processing the 2023a SSH mapping data challenge. Note that this data challenge is a somewhat extended version of the data challenge 2021a_SSH_mapping_OSE on a global scale.
show_downloads: true
google_analytics:
